{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "alo.fullname" . }}
  labels:
    {{- include "alo.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.gateway.host }}
    - host: {{ .Values.ingress.gateway.host }}
      http:
        paths:
          - path: {{ .Values.ingress.gateway.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "alo.fullname" . }}-gateway
                port:
                  name: http
    {{- end }}
    {{- if and .Values.kibana.enabled .Values.ingress.kibana.host }}
    - host: {{ .Values.ingress.kibana.host }}
      http:
        paths:
          - path: {{ .Values.ingress.kibana.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "alo.fullname" . }}-kibana
                port:
                  name: http
    {{- end }}
    {{- if and (not .Values.nifi.external.enabled) .Values.ingress.nifi.host }}
    - host: {{ .Values.ingress.nifi.host }}
      http:
        paths:
          - path: {{ .Values.ingress.nifi.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "alo.fullname" . }}-nifi
                port:
                  name: https
    {{- end }}
{{- end }}
