{{- if and .Values.ingress.enabled (eq (include "alo.kibanaEffective" .) "true") .Values.ingress.kibana.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "alo.fullname" . }}-kibana
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "kibana") | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.kibana.host }}
      http:
        paths:
          - path: {{ .Values.ingress.kibana.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "alo.fullname" . }}-kibana
                port:
                  name: http
{{- end }}
