{{- if and (eq (include "alo.kibanaEffective" .) "true") .Values.route.enabled .Values.route.kibana.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "alo.fullname" . }}-kibana
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "kibana") | nindent 4 }}
  {{- include "alo.routeAnnotations" (dict "global" .Values.route.annotations "local" .Values.route.kibana.annotations) | nindent 2 }}
spec:
  {{- if .Values.route.kibana.host }}
  host: {{ .Values.route.kibana.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "alo.fullname" . }}-kibana
    weight: 100
  port:
    targetPort: http
  {{- include "alo.routeTls" (dict "global" .Values.route.tls "local" .Values.route.kibana.tls) | nindent 2 }}
{{- end }}
