{{- if and .Values.route.enabled (eq (include "alo.kibanaEffective" .) "true") .Values.route.kibana.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "alo.fullname" . }}-kibana
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "kibana") | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.kibana.host }}
  host: {{ .Values.route.kibana.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "alo.fullname" . }}-kibana
    weight: 100
  port:
    targetPort: http
  {{- with .Values.route.tls }}
  tls:
    termination: {{ .termination }}
    {{- if .insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy }}
    {{- end }}
  {{- end }}
{{- end }}
