{{- if eq (include "alo.metricbeatEffective" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alo.fullname" . }}-metricbeat
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "metricbeat") | nindent 4 }}
spec:
  replicas: {{ .Values.metricbeat.replicas }}
  selector:
    matchLabels:
      {{- include "alo.selectorLabels" (dict "ctx" . "component" "metricbeat") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alo.labels" . | nindent 8 }}
        {{- include "alo.selectorLabels" (dict "ctx" . "component" "metricbeat") | nindent 8 }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/metricbeat/configmap.yaml") . | sha256sum }}
        {{- with .Values.metricbeat.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "alo.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- include "alo.imagePullSecrets" $ | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: metricbeat
          image: "{{ .Values.metricbeat.image.repository }}:{{ .Values.metricbeat.image.tag }}"
          imagePullPolicy: {{ .Values.metricbeat.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args: ["--strict.perms=false"]
          {{- if eq (include "alo.esAuthEnabled" .) "true" }}
          env:
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "alo.esAuthSecretName" . | trim }}
                  key: username
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "alo.esAuthSecretName" . | trim }}
                  key: password
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/metricbeat/metricbeat.yml
              subPath: metricbeat.yml
              readOnly: true
            {{- if eq (include "alo.esCaEnabled" .) "true" }}
            - name: es-ca
              mountPath: /etc/ssl/es
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.metricbeat.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "alo.fullname" . }}-metricbeat
        {{- if eq (include "alo.esCaEnabled" .) "true" }}
        - name: es-ca
          secret:
            secretName: {{ include "alo.esCaSecretName" . }}
        {{- end }}
      {{- include "alo.scheduling" .Values.metricbeat | nindent 6 }}
{{- end }}
