{{- if and (eq .Values.pipelineMode "nifi") (not .Values.nifi.external.enabled) .Values.nifi.flow.seedEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alo.fullname" . }}-nifi-flow
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "nifi") | nindent 4 }}
binaryData:
  flow.json.gz: {{ .Files.Get "files/nifi-seed-flow.json.gz" | b64enc }}
{{- end }}
