{{- if and .Values.route.enabled (eq .Values.pipelineMode "nifi") (not .Values.nifi.external.enabled) .Values.route.nifi.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "alo.fullname" . }}-nifi
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "nifi") | nindent 4 }}
  {{- include "alo.routeAnnotations" (dict "global" .Values.route.annotations "local" .Values.route.nifi.annotations) | nindent 2 }}
spec:
  {{- if .Values.route.nifi.host }}
  host: {{ .Values.route.nifi.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "alo.fullname" . }}-nifi
    weight: 100
  port:
    targetPort: https
  {{- include "alo.routeTls" (dict "global" .Values.route.tls "local" .Values.route.nifi.tls) | nindent 2 }}
{{- end }}
