{{- if and (eq .Values.pipelineMode "nifi") (not .Values.nifi.external.enabled) (not .Values.nifi.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alo.fullname" . }}-nifi
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "nifi") | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.nifi.auth.username | quote }}
  password: {{ .Values.nifi.auth.password | quote }}
  sensitivePropsKey: {{ .Values.nifi.sensitivePropsKey | quote }}
{{- end }}
