{{- if and (eq .Values.pipelineMode "logstash") (not .Values.logstash.external.enabled) .Values.logstash.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "alo.fullname" . }}-logstash
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "logstash") | nindent 4 }}
spec:
  {{- if .Values.logstash.pdb.minAvailable }}
  minAvailable: {{ .Values.logstash.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.logstash.pdb.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "alo.selectorLabels" (dict "ctx" . "component" "logstash") | nindent 6 }}
{{- end }}
