{{- if and (eq .Values.pipelineMode "logstash") (not .Values.logstash.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alo.fullname" . }}-logstash
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "logstash") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.logstash.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.logstash.service.monitoringPort }}
      targetPort: monitoring
      protocol: TCP
      name: monitoring
  selector:
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "logstash") | nindent 4 }}
{{- end }}
