{{- if and (eq .Values.pipelineMode "logstash") (not .Values.logstash.external.enabled) (or .Values.logstash.exporter.enabled (eq (include "alo.exportersEffective" .) "true")) .Values.serviceMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "alo.fullname" . }}-logstash
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "logstash") | nindent 4 }}
    {{- with .Values.serviceMonitors.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "alo.selectorLabels" (dict "ctx" . "component" "logstash") | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitors.interval }}
{{- end }}
