{{- if and .Values.gateway.elasticsearch.url .Values.gateway.elasticsearch.auth.enabled (not .Values.gateway.elasticsearch.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alo.fullname" . }}-gateway-es-auth
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.gateway.elasticsearch.auth.type "basic" }}
  username: {{ required "gateway.elasticsearch.auth.username is required" .Values.gateway.elasticsearch.auth.username | quote }}
  password: {{ required "gateway.elasticsearch.auth.password is required" .Values.gateway.elasticsearch.auth.password | quote }}
  {{- else if eq .Values.gateway.elasticsearch.auth.type "apiKey" }}
  apiKey: {{ required "gateway.elasticsearch.auth.apiKey is required" .Values.gateway.elasticsearch.auth.apiKey | quote }}
  {{- end }}
{{- end }}
