{{- if and .Values.gateway.elasticsearch.url .Values.gateway.elasticsearch.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alo.gatewayEsCaSecretName" . }}
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ required "gateway.elasticsearch.tls.caCert is required when tls.create=true" .Values.gateway.elasticsearch.tls.caCert | b64enc | quote }}
{{- end }}
