{{- if and .Values.elasticsearch.external.enabled .Values.elasticsearch.external.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alo.esCaSecretName" . }}
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ required "elasticsearch.external.tls.caCert is required when tls.create=true" .Values.elasticsearch.external.tls.caCert | b64enc | quote }}
{{- end }}
