apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alo.fullname" . }}-analyzer
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "analyzer") | nindent 4 }}
spec:
  replicas: {{ .Values.analyzer.replicas }}
  selector:
    matchLabels:
      {{- include "alo.selectorLabels" (dict "ctx" . "component" "analyzer") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alo.labels" . | nindent 8 }}
        {{- include "alo.selectorLabels" (dict "ctx" . "component" "analyzer") | nindent 8 }}
      {{- with .Values.analyzer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "alo.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- include "alo.imagePullSecrets" $ | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: analyzer
          image: "{{ .Values.analyzer.image.repository }}:{{ .Values.analyzer.image.tag }}"
          imagePullPolicy: {{ .Values.analyzer.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- with .Values.analyzer.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.analyzer.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            {{- toYaml .Values.analyzer.resources | nindent 12 }}
      {{- include "alo.scheduling" .Values.analyzer | nindent 6 }}
