{{- if and (eq (include "alo.clickhouseAuthEnabled" .) "true") (not .Values.clickhouse.external.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ch-auth" (include "alo.fullname" .) }}
  labels:
    {{- include "alo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.clickhouse.external.enabled }}
  username: {{ .Values.clickhouse.external.auth.username | default "default" | quote }}
  password: {{ .Values.clickhouse.external.auth.password | quote }}
  {{- else }}
  username: {{ .Values.clickhouse.auth.username | default "default" | quote }}
  password: {{ .Values.clickhouse.auth.password | quote }}
  {{- end }}
{{- end }}
