{{- if and .Values.clickhouse.external.enabled .Values.clickhouse.external.tls.create .Values.clickhouse.external.tls.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ch-ca" (include "alo.fullname" .) }}
  labels:
    {{- include "alo.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
    {{- .Values.clickhouse.external.tls.caCert | nindent 4 }}
{{- end }}
