{{- if not .Values.elasticsearch.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alo.fullname" . }}-elasticsearch
  labels:
    {{- include "alo.labels" . | nindent 4 }}
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "elasticsearch") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.elasticsearch.exporter.enabled }}
    - port: {{ .Values.elasticsearch.exporter.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "alo.selectorLabels" (dict "ctx" . "component" "elasticsearch") | nindent 4 }}
{{- end }}
